<?php require('includes/application_top.php');

// From

	$oid =1002;
       $rfq_order = tep_db_query("select * from rfq_order where rfq_id = '" . (int)$oid . "'");
    	$rfq_order_detail = tep_db_fetch_array($rfq_order); 
	
	    $rfq_id = tep_db_prepare_input($rfq_order_detail['rfq_id']);
        $manfacturer_name = getManfct_name($rfq_order_detail['manufacturer']);
        $serial = tep_db_prepare_input($rfq_order_detail['serial']);
        $model = tep_db_prepare_input($rfq_order_detail['model']);
       $issue_no = tep_db_prepare_input($rfq_order_detail['issue_no']);
        $po_no = tep_db_prepare_input($rfq_order_detail['po_no']);
        $notes = tep_db_prepare_input($rfq_order_detail['notes']); 
		$custm = tep_db_fetch_array(tep_db_query("select * from customers where customers_id = '" . (int)$rfq_order_detail['customer_id'] . "'"));
 
 $headers = "From:saeed_awan86@hotmail.com" . "\r\n";
        $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
 
 
$email ='<div style="width:80%;margin: 10px;padding: 15px;border: 2px solid #D4D9D4;"><h1>ORDER Detail NO: '.$rfq_id.'</h1><br>';
$email .='<h3>Customer Detail</h3><div>'; 
$email .= '<table width="100%" cellspacing="0" cellpadding="10" border="0" style="font-family:Arial, Helvetica, sans-serif;  color:#666;
font-size:12px;
background:#eaebec;
margin:0px;
padding:0px !important;
border:#ccc 1px solid;
border-radius:3px;
"> <tbody>';
$email .= '<tr style="text-align: center;
 padding-left:20px;">';
$email .= '<th style="padding:5px 5px 5px 5px;
 border-top:1px solid #fafafa;
 border-bottom:1px solid #e0e0e0;
 background: #ededed;">Name</th>';
$email .= '<td align="left" style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.$custm['customers_firstname']. ' '.$custm['customers_lastname'].'</td></tr>';
$email .= '<tr style="text-align: center;
 padding-left:20px;">';
$email .= '<th style="padding:5px 5px 5px 5px;
 border-top:1px solid #fafafa;
 border-bottom:1px solid #e0e0e0;
 background: #ededed;">Email</th>';
$email .= '<td align="left" style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.$custm['customers_email_address'].'</td></tr>';
$email .= '<tr style="text-align: center;
 padding-left:20px;">';
$email .= '<th style="padding:5px 5px 5px 5px;
 border-top:1px solid #fafafa;
 border-bottom:1px solid #e0e0e0;
 background: #ededed;">Group</th>';
$email .= '<td align="left" style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.get_customer_group($custm['customer_group_id']).'</td></tr></tbody></table>'; 
$email .= '<h3>Order Detail</h3>'; 
$email .= '<table width="100%" cellspacing="0" cellpadding="10" border="0" style="font-family:Arial, Helvetica, sans-serif;  color:#666;
font-size:12px;
background:#eaebec;
margin:0px;
padding:0px !important;
border:#ccc 1px solid;
border-radius:3px;"> <tbody>'; 
$email .= '<tr style="text-align: center;
 padding-left:20px;">';
$email .= '<th style="padding:5px 5px 5px 5px;
 border-top:1px solid #fafafa;
 border-bottom:1px solid #e0e0e0;
 background: #ededed;">Manfacturer</th>';
$email .= '<td align="left" style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.$manfacturer_name.'</td>';
$email .= '<th style="padding:5px 5px 5px 5px;
 border-top:1px solid #fafafa;
 border-bottom:1px solid #e0e0e0;
 background: #ededed;">Serial</th>';
$email .= '<td align="left" style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.$serial.'</td></tr>';
$email .= '<tr style="text-align: center;
 padding-left:20px;">';
$email .= '<th style="padding:5px 5px 5px 5px;
 border-top:1px solid #fafafa;
 border-bottom:1px solid #e0e0e0;
 background: #ededed;">Model</th>';
$email .= '<td align="left" style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.$model.'</td>';
$email .= '<th style="padding:5px 5px 5px 5px;
 border-top:1px solid #fafafa;
 border-bottom:1px solid #e0e0e0;
 background: #ededed;">Issue No</th>';
$email .= '<td align="left" style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.$issue_no.'</td></tr>';
$email .= '<tr style="text-align: center;
 padding-left:20px;">';
$email .= '<th style="padding:5px 5px 5px 5px;
 border-top:1px solid #fafafa;
 border-bottom:1px solid #e0e0e0;
 background: #ededed;">PO No</th>';
$email .= '<td align="left" style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.$po_no.'</td>';
$email .= '<th style="padding:5px 5px 5px 5px;
 border-top:1px solid #fafafa;
 border-bottom:1px solid #e0e0e0;
 background: #ededed;">Notes</th>';
$email .= '<td align="left" style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.$notes.'</td></tr>';
$email .= '<tr style="padding-left: 20px;
    text-align: center;color: #666;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px;
    text-shadow: 1px 1px 0 #fff;">';
$email .= '<td colspan="4" style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">';
$email .= '<table width="100%" cellspacing="0" cellpadding="10" border="0" style="font-family:Arial, Helvetica, sans-serif;  color:#666;
font-size:12px;
background:#eaebec;
margin:0px;
padding:0px !important;
border:#ccc 1px solid;
border-radius:3px;"> <tbody>';
$email .= '<tbody>';
$email .= '<tr  height="15px" style="padding-left: 20px;
    text-align: center;color: #666;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px;
    text-shadow: 1px 1px 0 #fff;">';
$email .= '<th style="padding-left: 10px;
    text-align: left; 
    border-bottom: 1px solid #e0e0e0;
    border-top: 1px solid #fafafa; color: #666;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px"><strong style="text-align: left;">Qty</strong></th>';
$email .= '<th style="padding-left: 10px;
    text-align: left; 
    border-bottom: 1px solid #e0e0e0;
    border-top: 1px solid #fafafa; color: #666;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px"><strong style="text-align: center; color: #666;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px;">Part Type</strong></th>';
$email .= '<th style="padding-left: 10px;
    text-align: left; 
    border-bottom: 1px solid #e0e0e0;
    border-top: 1px solid #fafafa; color: #666;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px"><strong style="text-align: center; color: #666;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px;">Description</strong></th>';
$email .= '<th style="padding-left: 10px;
    text-align: left; 
    border-bottom: 1px solid #e0e0e0;
    border-top: 1px solid #fafafa; color: #666;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px"><strong style="text-align: center; color: #666;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px;">Part Number</strong></th>';
$email .= '<th style="padding-left: 10px;
    text-align: left; 
    border-bottom: 1px solid #e0e0e0;
    border-top: 1px solid #fafafa; color: #666;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px"><strong style="text-align: center; color: #666;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 12px;">Price</strong></th></tr>';

$rfq_order_items = tep_db_query("select * from rfq_order_detail where rfq_id = '" . (int)$rfq_order_detail['rfq_id'] . "'");
       while ($rfq_order_items_detail = tep_db_fetch_array($rfq_order_items)){
$email .= '<tr  height="25px" style="'.$inner_tr.'">';
$email .= '<td style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.$rfq_order_items_detail['qty'].'</td>';
$email .= '<td style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.$rfq_order_items_detail['part_type'].' </td>';
$email .= '<td style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.$rfq_order_items_detail['description'].' </td>';
$email .= '<td style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.$rfq_order_items_detail['description'].'</td>';
$email .= '<td style="padding:10px;
 border-top: 1px solid #ffffff;
 border-bottom:1px solid #e0e0e0;
 border-left: 1px solid #e0e0e0;
 background: #fafafa;">'.$rfq_order_items_detail['description'].'</td> </tr>';
	   }
$email .='</tbody></table></td></tr>';
$email .='</tbody></table>';
$email .='</div></div>';

//echo $email;
$header="from: saeed_awan86@hotmail.com";
 
// Enter your email address
 //$to =$email;
  $to ="saeed_awan86@hotmail.com" . "\r\n";;

$send_contact=mail($to,"Staples",$email,$headers);
 
?>